name: trusttunnel
description: "Mobile VPN client for Android and iOS, built with Flutter"

publish_to: 'none'

version: 1.0.1+3501

version_titles:
  versionTitleReleaseNumber: 1
  versionTitleRcNumber: 0
  versionTitleBetaNumber: 0
  versionTitleNightlyNumber: 1
  versionTitlePreNightlyNumber: 0

# build_channel defines the current CI build track.
# Input value from bamboo managed in bamboo-specs/scripts/configure_before_ios_build.sh script
# resulting value updates this variable before building the app
# Possible values:
#   - Release (default)
#   - Rc
#   - Beta
#   - Nightly
#   - PreNightly
build_channel: Release

environment:
  flutter: 3.38.3
  sdk: 3.10.1

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter
  intl_utils: 2.8.13
  rxdart: 0.28.0
  package_info_plus: 9.0.0
  url_launcher: 6.3.2
  drift: 2.30.0
  path_provider: 2.1.5
  punycoder: 0.2.2
  vpn_plugin:
    path: plugins/vpn_plugin
  sqlite3_flutter_libs: 0.5.41
  html: 0.15.6
  flutter_native_splash: 2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: 2.30.0
  flutter_lints: 6.0.0
  build_runner: 2.10.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/IconFont.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

flutter_intl:
  enabled: true
  generate: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/common/localization/arb
  output_dir: lib/common/localization/generated
  use_deferred_loading: false